language: node_js
node_js:
  - '8'
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  # - ng test --project=ngmat-sorted-table --browsers ChromeHeadless
  # - ng test --project=ngmat-overlay-spinner --browsers ChromeHeadless
  - npm run package
  # - xvfb-run npm run e2e
  # - npm run build-demo
  - ng build --project=demos-app --prod --deploy-url=https://crusaider.github.io/angular-material-utils/ --base-href=/angular-material-utils/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist/demos-app
  on:
    branch: master
